-- SUHAS GROUP PRODUCTION SECURITY FOUNDATION
-- Run once in Supabase SQL Editor AFTER your existing schema.sql.
-- Safe/idempotent design: CREATE IF NOT EXISTS + DROP POLICY IF EXISTS.
-- Owner bootstrap email: suhasgroup.in@gmail.com
--
-- IMPORTANT:
-- 1) This script does NOT expose any API secret.
-- 2) Never put service/secret keys in frontend code.
-- 3) Review existing application-specific RLS policies before production launch.

BEGIN;

-- ---------------------------------------------------------
-- 1. Job source fields
-- ---------------------------------------------------------
ALTER TABLE IF EXISTS public.jobs
  ADD COLUMN IF NOT EXISTS source text DEFAULT 'SUHAS GROUP';

ALTER TABLE IF EXISTS public.jobs
  ADD COLUMN IF NOT EXISTS external_url text;

-- ---------------------------------------------------------
-- 2. Saved jobs
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.saved_jobs (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  job_id bigint NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, job_id)
);

ALTER TABLE public.saved_jobs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage own saved jobs" ON public.saved_jobs;
CREATE POLICY "Users can manage own saved jobs"
ON public.saved_jobs
FOR ALL TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- ---------------------------------------------------------
-- 3. Role table
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_roles (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'USER'
    CHECK (role IN ('OWNER','ADMIN','EDITOR','USER')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------
-- 4. Secure role helper
-- ---------------------------------------------------------
CREATE OR REPLACE FUNCTION public.has_suhas_role(
  p_user_id uuid,
  p_roles text[]
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles ur
    WHERE ur.user_id = p_user_id
      AND ur.role = ANY(p_roles)
  );
$$;

REVOKE ALL ON FUNCTION public.has_suhas_role(uuid, text[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.has_suhas_role(uuid, text[]) TO authenticated;

DROP POLICY IF EXISTS "Users can read own role" ON public.user_roles;
CREATE POLICY "Users can read own role"
ON public.user_roles
FOR SELECT TO authenticated
USING (
  auth.uid() = user_id
  OR public.has_suhas_role(auth.uid(), ARRAY['OWNER','ADMIN'])
);

DROP POLICY IF EXISTS "Only owner can manage roles" ON public.user_roles;
CREATE POLICY "Only owner can manage roles"
ON public.user_roles
FOR ALL TO authenticated
USING (public.has_suhas_role(auth.uid(), ARRAY['OWNER']))
WITH CHECK (public.has_suhas_role(auth.uid(), ARRAY['OWNER']));

-- ---------------------------------------------------------
-- 5. Automatically assign USER on signup.
-- Owner email is bootstrapped as OWNER.
-- ---------------------------------------------------------
CREATE OR REPLACE FUNCTION public.suhas_handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.user_roles(user_id, role)
  VALUES (
    NEW.id,
    CASE
      WHEN lower(COALESCE(NEW.email,'')) = 'suhasgroup.in@gmail.com'
      THEN 'OWNER'
      ELSE 'USER'
    END
  )
  ON CONFLICT (user_id) DO UPDATE
    SET role = CASE
      WHEN lower(COALESCE(NEW.email,'')) = 'suhasgroup.in@gmail.com'
      THEN 'OWNER'
      ELSE public.user_roles.role
    END,
    updated_at = now();

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created_suhas_role
ON auth.users;

CREATE TRIGGER on_auth_user_created_suhas_role
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.suhas_handle_new_user();

-- Bootstrap Owner if the auth account already exists.
INSERT INTO public.user_roles(user_id, role)
SELECT id, 'OWNER'
FROM auth.users
WHERE lower(email) = 'suhasgroup.in@gmail.com'
ON CONFLICT (user_id) DO UPDATE
SET role = 'OWNER', updated_at = now();

-- ---------------------------------------------------------
-- 6. Audit logs
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  action text NOT NULL,
  entity_type text,
  entity_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_actor
  ON public.audit_logs(actor_user_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created
  ON public.audit_logs(created_at DESC);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Owner and admin can read audit logs"
ON public.audit_logs;

CREATE POLICY "Owner and admin can read audit logs"
ON public.audit_logs
FOR SELECT TO authenticated
USING (public.has_suhas_role(auth.uid(), ARRAY['OWNER','ADMIN']));

DROP POLICY IF EXISTS "No direct audit log writes"
ON public.audit_logs;

-- Intentionally no INSERT/UPDATE/DELETE policy for clients.
-- Server/Edge Functions should write audit records.

-- ---------------------------------------------------------
-- 7. AI usage logs
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ai_usage_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  request_type text NOT NULL,
  model text,
  usage_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'success',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_usage_logs_user
  ON public.ai_usage_logs(user_id);

CREATE INDEX IF NOT EXISTS idx_ai_usage_logs_created
  ON public.ai_usage_logs(created_at DESC);

ALTER TABLE public.ai_usage_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own AI usage"
ON public.ai_usage_logs;

CREATE POLICY "Users can read own AI usage"
ON public.ai_usage_logs
FOR SELECT TO authenticated
USING (
  auth.uid() = user_id
  OR public.has_suhas_role(auth.uid(), ARRAY['OWNER','ADMIN'])
);

-- No client INSERT/UPDATE/DELETE policy.
-- AI Edge Function should write usage logs.

-- ---------------------------------------------------------
-- 8. Site settings
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.site_settings (
  key text PRIMARY KEY,
  value jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read public site settings"
ON public.site_settings;

-- Only settings explicitly marked public=true are readable.
CREATE POLICY "Public can read public site settings"
ON public.site_settings
FOR SELECT
USING (COALESCE((value ->> 'public')::boolean, false) = true);

DROP POLICY IF EXISTS "Owner can manage site settings"
ON public.site_settings;

CREATE POLICY "Owner can manage site settings"
ON public.site_settings
FOR ALL TO authenticated
USING (public.has_suhas_role(auth.uid(), ARRAY['OWNER']))
WITH CHECK (public.has_suhas_role(auth.uid(), ARRAY['OWNER']));

-- ---------------------------------------------------------
-- 9. AI settings: never store the actual API key here.
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ai_settings (
  id boolean PRIMARY KEY DEFAULT true CHECK (id = true),
  enabled boolean NOT NULL DEFAULT true,
  provider text NOT NULL DEFAULT 'openai',
  model text,
  daily_user_limit integer NOT NULL DEFAULT 20
    CHECK (daily_user_limit BETWEEN 0 AND 100000),
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.ai_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read AI availability"
ON public.ai_settings;

CREATE POLICY "Authenticated users can read AI availability"
ON public.ai_settings
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Owner can manage AI settings"
ON public.ai_settings;

CREATE POLICY "Owner can manage AI settings"
ON public.ai_settings
FOR ALL TO authenticated
USING (public.has_suhas_role(auth.uid(), ARRAY['OWNER']))
WITH CHECK (public.has_suhas_role(auth.uid(), ARRAY['OWNER']));

-- ---------------------------------------------------------
-- 10. Admin job policy.
-- Existing public job-read policy is intentionally NOT deleted.
-- This adds server/database-side admin authorization.
-- ---------------------------------------------------------
ALTER TABLE IF EXISTS public.jobs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "SUHAS owner/admin/editor manage jobs"
ON public.jobs;

CREATE POLICY "SUHAS owner/admin/editor manage jobs"
ON public.jobs
FOR ALL TO authenticated
USING (
  public.has_suhas_role(
    auth.uid(),
    ARRAY['OWNER','ADMIN','EDITOR']
  )
)
WITH CHECK (
  public.has_suhas_role(
    auth.uid(),
    ARRAY['OWNER','ADMIN','EDITOR']
  )
);

-- ---------------------------------------------------------
-- 11. Admin read policies for applications/profiles.
-- Existing user/application policies are preserved.
-- ---------------------------------------------------------
ALTER TABLE IF EXISTS public.applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "SUHAS owner/admin read applications"
ON public.applications;

CREATE POLICY "SUHAS owner/admin read applications"
ON public.applications
FOR SELECT TO authenticated
USING (
  public.has_suhas_role(auth.uid(), ARRAY['OWNER','ADMIN'])
);

ALTER TABLE IF EXISTS public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "SUHAS owner/admin read profiles"
ON public.profiles;

CREATE POLICY "SUHAS owner/admin read profiles"
ON public.profiles
FOR SELECT TO authenticated
USING (
  public.has_suhas_role(auth.uid(), ARRAY['OWNER','ADMIN'])
);

-- ---------------------------------------------------------
-- 12. Helpful indexes
-- ---------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_saved_jobs_user
  ON public.saved_jobs(user_id);

CREATE INDEX IF NOT EXISTS idx_saved_jobs_job
  ON public.saved_jobs(job_id);

-- ---------------------------------------------------------
-- 13. Lock down public schema function creation.
-- ---------------------------------------------------------
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

COMMIT;

-- Verification:
SELECT
  u.email,
  ur.role,
  ur.created_at
FROM auth.users u
LEFT JOIN public.user_roles ur ON ur.user_id = u.id
WHERE lower(u.email) = 'suhasgroup.in@gmail.com';
